spring:
  datasource:
    url: jdbc:postgresql://eufloria-db-eufloria.a.aivencloud.com:11276/eufloria-db?ssl=require&user=avnadmin&password=AVNS_uqvvh_Eoem9yfHXpKeX
    username: avnadmin
    password: AVNS_uqvvh_Eoem9yfHXpKeX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true